#!/usr/bin/ruby
require 'shell'

installDir = File.expand_path(File.dirname(__FILE__))
argList = ARGV.join(" ")
if !argList.empty?
    exec("/usr/bin/ruby", "-KO", "-I#{installDir}/lib", "#{installDir}/bin/jldrill", argList)
else
    exec("/usr/bin/ruby", "-KO", "-I#{installDir}/lib", "#{installDir}/bin/jldrill")
end

