#!/usr/bin/ruby
require 'shell'

installDir = File.expand_path(File.dirname(__FILE__))
argList = ARGV.join(" ")
exec("/usr/bin/ruby", "-KO", "-I#{installDir}/lib", "#{installDir}/bin/jldrill", argList)

