#!/usr/bin/ruby
require 'shell'

installDir = File.expand_path(File.dirname(__FILE__))
argList = ARGV.join(" ")
if !argList.empty?
    exec("ruby1.9.1", "-KO", "-I#{installDir}/lib", "-rrubygems", "#{installDir}/bin/jldrill", argList)
else
    exec("ruby1.9.1", "-KO", "-I#{installDir}/lib", "-rrubygems", "#{installDir}/bin/jldrill")
end

