# Copyright (C) 2004-2005 Masao Mutoh, Laurent Sansonetti, Mathieu Blondel, 
#                         Mike Charlton

copyright = <<EOS
# This file is automatically generated by the installer.
# Do not edit by hands.
EOS

File.open('config.rb', 'w') do |file|
    file.print <<EOS

module JLDrill
  module Config
    MAIN_DATA_DIR = '#{config('data-dir')}'
    DATA_DIR = '#{config('data-dir')}/jldrill'
    LIB_DIR = '#{config('rb-dir')}'
  end
end
EOS
end

File.open('version.rb', 'w') do |file|
    begin
        version = IO.readlines('../../VERSION').join
    rescue Errno::ENOENT
        version = "CVS"
    end
    file.print <<EOS
# This file is automatically generated by the installer.
# Do not edit by hands.

module JLDrill
  VERSION = "#{version}"
end
EOS
end
